#############################################################################
# Generated by PAGE version 4.9
# in conjunction with Tcl version 8.6
set vTcl(timestamp) ""


set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #d9d9d9
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #d8d8d8
set vTcl(active_menu_fg) #000000
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top37
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    set site_3_0 $base.m45
    set site_3_0 $base.lab38
    set site_3_0 $base.lab46
    set site_3_0 $base.lab52
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# USER DEFINED PROCEDURES
#

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top37 {base} {
    if {$base == ""} {
        set base .top37
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m45" -background {#d9d9d9} -highlightbackground {#d9d9d9} \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 1168x1047+-1858+677
    update
    # set in toplevel.wgt.
    global vTcl
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 7192 2328
    wm minsize $top 208 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "SwipeSense Product Functional "
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    menu $top.m45 \
        -activebackground {#d8d8d8} -activeforeground {#000000} \
        -background {#d9d9d9} -font TkMenuFont -foreground {#000000} \
        -tearoff 0 
    $top.m45 add cascade \
        -menu "$top.m45.men37" -activebackground {#d9d9d9} \
        -activeforeground {#000000} -background {#d9d9d9} -font TkMenuFont \
        -foreground {#000000} -label Settings 
    set site_3_0 $top.m45
    menu $site_3_0.men37 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font {{Segoe UI} 9} -foreground black \
        -tearoff 0 
    $site_3_0.men37 add command \
        -activebackground {#d8d8d8} -activeforeground {#000000} \
        -background {#d9d9d9} -command {# TODO} -font TkMenuFont \
        -foreground {#000000} -label Database 
    $site_3_0.men37 add command \
        -activebackground {#d8d8d8} -activeforeground {#000000} \
        -background {#d9d9d9} -command {# TODO} -font TkMenuFont \
        -foreground {#000000} -label {Serial Port} 
    $site_3_0.men37 add command \
        -activebackground {#d8d8d8} -activeforeground {#000000} \
        -background {#d9d9d9} -command {# TODO} -font TkMenuFont \
        -foreground {#000000} -label Extra 
    labelframe $top.lab38 \
        -foreground black -text DateTime -background {#d9d9d9} -height 165 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 1120 
    vTcl:DefineAlias "$top.lab38" "Labelframe1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.lab38
    message $site_3_0.mes39 \
        -anchor w -background {#d9d9d9} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text pending... \
        -width 219 
    vTcl:DefineAlias "$site_3_0.mes39" "MessageDB" vTcl:WidgetProc "Toplevel1" 1
    message $site_3_0.mes40 \
        -anchor w -background {#d9d9d9} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text pending... \
        -width 100 
    vTcl:DefineAlias "$site_3_0.mes40" "MessageDBS" vTcl:WidgetProc "Toplevel1" 1
    message $site_3_0.mes42 \
        -anchor w -background {#d9d9d9} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text unknown \
        -width 179 
    vTcl:DefineAlias "$site_3_0.mes42" "MessageTF" vTcl:WidgetProc "Toplevel1" 1
    message $site_3_0.mes43 \
        -anchor w -background {#d9d9d9} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text unknown: \
        -width 219 
    vTcl:DefineAlias "$site_3_0.mes43" "MessageTS" vTcl:WidgetProc "Toplevel1" 1
    message $site_3_0.mes44 \
        -anchor w -background {#d9d9d9} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text unknown \
        -width 249 
    vTcl:DefineAlias "$site_3_0.mes44" "MessageWO" vTcl:WidgetProc "Toplevel1" 1
    message $site_3_0.mes45 \
        -anchor w -background {#d9d9d9} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text unknown \
        -width 150 
    vTcl:DefineAlias "$site_3_0.mes45" "MessagePN" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab37 \
        -anchor w -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -justify left -text {Database: } 
    vTcl:DefineAlias "$site_3_0.lab37" "Label1" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab38 \
        -anchor w -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -justify left -text Status: 
    vTcl:DefineAlias "$site_3_0.lab38" "Label2" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab39 \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -text {Test Station: } 
    vTcl:DefineAlias "$site_3_0.lab39" "Label3" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab40 \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -text {Test Fixture: } 
    vTcl:DefineAlias "$site_3_0.lab40" "Label4" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab41 \
        -anchor w -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -text {Work Order: } 
    vTcl:DefineAlias "$site_3_0.lab41" "Label5" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab42 \
        -anchor w -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -text {Part Number:} 
    vTcl:DefineAlias "$site_3_0.lab42" "Label6" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.mes39 \
        -in $site_3_0 -x 140 -y 40 -width 219 -relwidth 0 -height 44 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.mes40 \
        -in $site_3_0 -x 90 -y 90 -width 219 -anchor nw -bordermode ignore 
    place $site_3_0.mes42 \
        -in $site_3_0 -x 500 -y 90 -width 179 -relwidth 0 -height 44 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.mes43 \
        -in $site_3_0 -x 500 -y 40 -width 219 -relwidth 0 -height 44 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.mes44 \
        -in $site_3_0 -x 840 -y 40 -width 249 -relwidth 0 -height 44 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.mes45 \
        -in $site_3_0 -x 840 -y 90 -width 249 -anchor nw -bordermode ignore 
    place $site_3_0.lab37 \
        -in $site_3_0 -x 20 -y 40 -width 104 -relwidth 0 -height 46 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab38 \
        -in $site_3_0 -x 20 -y 90 -width 68 -relwidth 0 -height 46 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab39 \
        -in $site_3_0 -x 370 -y 40 -width 126 -relwidth 0 -height 46 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab40 \
        -in $site_3_0 -x 370 -y 90 -width 115 -relwidth 0 -height 46 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab41 \
        -in $site_3_0 -x 700 -y 40 -width 135 -relwidth 0 -height 46 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab42 \
        -in $site_3_0 -x 700 -y 90 -width 135 -relwidth 0 -height 46 \
        -relheight 0 -anchor nw -bordermode ignore 
    labelframe $top.lab46 \
        -foreground black -text {PRODUCTION FUNCTION} -background {#d9d9d9} \
        -height 255 -highlightbackground {#d9d9d9} -highlightcolor black \
        -width 1110 
    vTcl:DefineAlias "$top.lab46" "Labelframe2" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.lab46
    message $site_3_0.mes47 \
        -background {#d9d9d9} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {PLACE UNIT ON FIXTURE AND SCAN TO START TEST..} -width 574 
    vTcl:DefineAlias "$site_3_0.mes47" "MessageOP" vTcl:WidgetProc "Toplevel1" 1
    message $site_3_0.mes48 \
        -background {#d9d9d9} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Message \
        -width 100 
    vTcl:DefineAlias "$site_3_0.mes48" "Message9" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent49 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$site_3_0.ent49" "Entry1" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but50 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text Button 
    vTcl:DefineAlias "$site_3_0.but50" "Button1" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but51 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text Button 
    vTcl:DefineAlias "$site_3_0.but51" "Button2" vTcl:WidgetProc "Toplevel1" 1
    checkbutton $site_3_0.che58 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify left -text {OPTION 1} -variable che58 
    vTcl:DefineAlias "$site_3_0.che58" "CheckOption1" vTcl:WidgetProc "Toplevel1" 1
    checkbutton $site_3_0.che59 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify left -text {OPTION 2} -variable che59 
    vTcl:DefineAlias "$site_3_0.che59" "CheckOption2" vTcl:WidgetProc "Toplevel1" 1
    ttk::progressbar $site_3_0.tPr60 \
        -variable TestProgress 
    vTcl:DefineAlias "$site_3_0.tPr60" "TProgressbar" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.mes47 \
        -in $site_3_0 -x 200 -y 40 -width 574 -relwidth 0 -height 44 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.mes48 \
        -in $site_3_0 -x 10 -y 190 -anchor nw -bordermode ignore 
    place $site_3_0.ent49 \
        -in $site_3_0 -x 360 -y 130 -anchor nw -bordermode ignore 
    place $site_3_0.but50 \
        -in $site_3_0 -x 990 -y 70 -anchor nw -bordermode ignore 
    place $site_3_0.but51 \
        -in $site_3_0 -x 990 -y 160 -anchor nw -bordermode ignore 
    place $site_3_0.che58 \
        -in $site_3_0 -x 10 -y 80 -anchor nw -bordermode ignore 
    place $site_3_0.che59 \
        -in $site_3_0 -x 10 -y 130 -anchor nw -bordermode ignore 
    place $site_3_0.tPr60 \
        -in $site_3_0 -x 360 -y 210 -width 290 -relwidth 0 -height 22 \
        -relheight 0 -anchor nw -bordermode ignore 
    labelframe $top.lab52 \
        -foreground black -text RESULTS -background {#d9d9d9} -height 355 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 1090 
    vTcl:DefineAlias "$top.lab52" "Labelframe3" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.lab52
    text $site_3_0.tex53 \
        -background {#c0c0c0} -font TkTextFont -foreground black -height 284 \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -width 314 -wrap word 
    .top37.lab52.tex53 configure -font TkTextFont
    .top37.lab52.tex53 insert end text
    vTcl:DefineAlias "$site_3_0.tex53" "TextResults" vTcl:WidgetProc "Toplevel1" 1
    canvas $site_3_0.can54 \
        -background white -borderwidth 2 -closeenough 1.0 -height 291 \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -relief ridge -selectbackground {#c4c4c4} \
        -selectforeground black -width 509 
    vTcl:DefineAlias "$site_3_0.can54" "Canvas1" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but55 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text Button 
    vTcl:DefineAlias "$site_3_0.but55" "Button3" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but56 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text Button 
    vTcl:DefineAlias "$site_3_0.but56" "Button4" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.tex53 \
        -in $site_3_0 -x 30 -y 60 -width 314 -relwidth 0 -height 284 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.can54 \
        -in $site_3_0 -x 380 -y 60 -width 509 -relwidth 0 -height 284 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but55 \
        -in $site_3_0 -x 980 -y 110 -anchor nw -bordermode ignore 
    place $site_3_0.but56 \
        -in $site_3_0 -x 980 -y 240 -anchor nw -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab38 \
        -in $top -x 20 -y 30 -width 1120 -relwidth 0 -height 165 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab46 \
        -in $top -x 30 -y 230 -width 1110 -relwidth 0 -height 255 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab52 \
        -in $top -x 30 -y 520 -width 1090 -relwidth 0 -height 355 \
        -relheight 0 -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

Window show .
Window show .top37

