#! /usr/bin/env python
#
# Support module generated by PAGE version 4.9
# In conjunction with Tcl version 8.6
#    May 03, 2017 04:57:57 PM


import sys
import ssTestClass
from ssTestClass import checkBarcodeData
from array import array

station = ssTestClass.TestStation()   
fixture = ssTestClass.ProductionFixture()
#UUT = ssTestClass.barcode()
 
try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

def set_Tk_var():
    global che58
    che58 = StringVar()
    global che59
    che59 = StringVar()
    global TestProgress
    TestProgress = IntVar()
    global barCodeEntry
    barCodeEntry = StringVar()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top     
    w.MessageOP.configure(text = station.initialize())
    w.MessageTS.configure(text = station.stationID)
    fixture.initialize()
    w.MessageTF.configure(text = fixture.function)

def clearBarCodeFields():
    w.MessageWO.configure(text ="")
    w.MessagePN.configure(text = "")
    
    pass
        
    
    
def configDataBase():
    pass

def configSerialPort():
    pass

def extraMenuItem():
    pass


def getBarcodeEntry(object):   
    UUT = ssTestClass.checkBarcodeData(barCodeEntry.get())
    w.Message9.configure(text = UUT.HWID)  #not sure about this one
    w.MessageWO.configure(text = UUT.workOrder )
    w.MessagePN.configure(text =  UUT.partNumber )
    pass

def button4OnClick(p1):
    print('testform_support.onClick')
    sys.stdout.flush()
    sys.exit()

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import testform 
#    import ssTestClass
   
    testform.vp_start_gui()
 


